# Generated by Django 4.2.7 on 2023-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
    ]
